server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: circuit-all
          uri: http://${CIRCUIT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/circuit
            - Method=GET
          filters:
            - SetPath=/api/circuit
        - id: circuit-id
          uri: http://${CIRCUIT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/circuit/{id}
            - Method=GET
          filters:
            - SetPath=/api/circuit/{id}
        - id: team-all
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/team
            - Method=GET
          filters:
            - SetPath=/api/team
        - id: team-id
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/team/{id}
            - Method=GET
          filters:
            - SetPath=/api/team/{id}
        - id: driver-id
          uri: http://${DRIVER_SERVICE_BASEURL:localhost:8079}
          predicates:
            - Path=/driver/{teamId}
            - Method=GET
          filters:
            - SetPath=/api/driver/{teamId}
        - id: race-all
          uri: http://${RACE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/race
            - Method=GET,POST
          filters:
            - SetPath=/api/race
        - id: race-id
          uri: http://${RACE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/race/{id}
            - Method=GET,PUT,DELETE
          filters:
            - SetPath=/api/race/{id}